//! Shared types for guidance — FileType, MemberType, Member, Stage, QueryResult, etc.
const std = @import("std");
const common = @import("common");
const json_writer = @import("sync/json_writer.zig");

/// File type enum for source, markdown, config, data, pdf, audio, unknown.
pub const FileType = enum {
    source, // Zig, Python, Rust, Go, etc.
    markdown, // .md, .markdown
    config, // .json, .toml, .yaml, .ini, .env
    data, // structured data not fitting other categories
    pdf, // future: pdftotext extraction
    audio, // future: whisper transcript
    unknown,

    /// Infer FileType from a file extension.
    pub fn fromExtension(ext: []const u8) FileType {
        const known_source = [_][]const u8{
            ".zig", ".zon",  ".py",    ".rs",  ".go", ".ts",  ".tsx",
            ".js",  ".jsx",  ".c",     ".cpp", ".h",  ".hpp", ".lua",
            ".rb",  ".java", ".swift", ".kt",
        };
        const known_markdown = [_][]const u8{ ".md", ".markdown", ".mdx" };
        const known_config = [_][]const u8{
            ".json", ".toml", ".yaml", ".yml", ".ini", ".env", ".cfg", ".conf",
        };

        for (known_source) |e| if (std.ascii.eqlIgnoreCase(ext, e)) return .source;
        for (known_markdown) |e| if (std.ascii.eqlIgnoreCase(ext, e)) return .markdown;
        for (known_config) |e| if (std.ascii.eqlIgnoreCase(ext, e)) return .config;
        return .unknown;
    }

    /// Return the canonical string stored in the `file_type` DB column.
    pub fn toStr(self: FileType) []const u8 {
        return switch (self) {
            .source => "source",
            .markdown => "markdown",
            .config => "config",
            .data => "data",
            .pdf => "pdf",
            .audio => "audio",
            .unknown => "unknown",
        };
    }
};

/// AST member type enum (fn_decl, struct, enum, etc.).
pub const MemberType = enum {
    fn_decl,
    fn_private,
    @"struct",
    @"enum",
    @"union",
    enum_field,
    test_decl,
    comptime_block,
    method,
    method_private,
};

pub const PatternType = common.pattern.PatternType;
pub const Pattern = common.pattern.Pattern;

/// Function parameter (name, optional type, optional default value).
pub const Param = struct {
    name: []const u8,
    type: ?[]const u8 = null,
    default: ?[]const u8 = null,
};

/// A parsed AST declaration extracted from a source file.
pub const Member = struct {
    type: MemberType,
    name: []const u8,
    match_hash: ?[]const u8 = null,
    signature: ?[]const u8 = null,
    params: []const Param = &.{},
    returns: ?[]const u8 = null,
    /// Member-level description.
    ///
    /// Source of truth: the `///` doc comment block immediately above the
    /// declaration in the source file.  This JSON field is kept for backward
    /// compatibility with existing guidance JSON files and for file formats that
    /// cannot embed comments.  Use `guidance sync-comments` to move comments
    /// from JSON into source files.
    comment: ?[]const u8 = null,
    tags: []const []const u8 = &.{},
    patterns: []const Pattern = &.{},
    is_pub: bool = false,
    members: []const Member = &.{},
    /// Relative paths to files in other languages that implement the same interface.
    /// Example: "src/foo.zig" → equivalents: ["bin/foo.py"]
    /// Populated by sync when a sibling file with matching stem is found.
    equivalents: []const []const u8 = &.{},
    /// 1-based line number of the declaration in the source file.
    /// Verified against the AST on each sync; corrected automatically when stale.
    line: ?u32 = null,
    /// True when comment was generated by LLM (not present in source file).
    /// Used during comment-sync phase to write generated comments back to source.
    comment_generated: bool = false,
};

pub const Skill = struct {
    ref: []const u8,
    context: ?[]const u8 = null,
};

/// Defines a metadata structure for configuration; owned by the project; maintains invariant of being a static, compile-time defined type.
pub const Meta = struct {
    module: []const u8,
    source: []const u8,
    language: []const u8 = "zig",
};

/// Defines guidance documents with structured metadata; managed centrally, immutable once created.
pub const GuidanceDoc = struct {
    meta: Meta,
    /// Module-level one-line description.
    ///
    /// Source of truth: the `//!` doc comment block at the top of the source file.
    /// This JSON field is kept for backward compatibility and for non-Zig file
    /// formats that cannot embed comments.  Use `guidance sync-comments` to
    /// migrate from JSON comments to source comments.
    comment: ?[]const u8 = null,
    /// Comprehensive module documentation (<800 words), generated by thinking model.
    ///
    /// Source of truth: the `//!` doc comment block at the top of the source file.
    /// This JSON field is kept for backward compatibility.
    detail: ?[]const u8 = null,
    /// Discovery keywords for semantic search, generated by fast model.
    keywords: []const []const u8 = &.{},
    skills: []const Skill = &.{},
    capabilities: []const []const u8 = &.{},
    hashtags: []const []const u8 = &.{},
    used_by: []const []const u8 = &.{},
    members: []const Member = &.{},
    /// Relative paths to equivalent files in other languages (e.g. foo.zig ↔ foo.py).
    equivalents: []const []const u8 = &.{},
};

pub const FileMatch = struct {
    filename: []const u8,
    filepath: []const u8,
    description: []const u8 = "",
    line_context: []const u8 = "",
};

pub const GuidanceInfo = struct {
    path: []const u8,
    comment: []const u8 = "",
    functions: []const Member = &.{},
    classes: []const Member = &.{},
    skills: []const []const u8 = &.{},
    tags: []const []const u8 = &.{},
};

/// Tracks AST nodes with ownership model; ensures invariants on structure and mutability.
pub const ASTAnalysis = struct {
    filepath: []const u8,
    functions: []const Member = &.{},
    classes: []const Member = &.{},
    imports: []const []const u8 = &.{},
    patterns_detected: []const []const u8 = &.{},
    token_count: usize = 0,
    signature_preview: []const u8 = "",
};

/// Query result with file matches, AST analysis, and suggestions.
pub const QueryResult = struct {
    query: []const u8,
    file_matches: []const FileMatch = &.{},
    guidance_files: []const GuidanceInfo = &.{},
    ast_analysis: []const ASTAnalysis = &.{},
    intelligent_summary: []const u8 = "",
    related_skills: []const []const u8 = &.{},
    suggested_actions: []const []const u8 = &.{},
    insights: []const []const u8 = &.{},
    recent_capabilities: []const []const u8 = &.{},
};

// ---------------------------------------------------------------------------
// Staged explain pipeline types
// ---------------------------------------------------------------------------

/// Stage kind enum for the staged explain pipeline.
pub const StageKind = enum {
    /// Human-readable explanation from module or member comment.
    prose,
    /// Verbatim source code excerpt.  Never altered by LLM.
    code,
    /// Structured metadata: keywords, see_also, skills from guidance JSON.
    metadata,
    /// Matching bullet from INSIGHTS.md or CAPABILITIES.md.
    insight,
    /// Excerpt from a SKILL.md document.
    skill_doc,
    /// Excerpt from a CAPABILITY.md file.
    capability_doc,
    /// M7: Sentinel — no relevant results found for this query.
    /// The pipeline should skip synthesis and cache when this kind appears.
    not_found,
};

/// A single stage in the staged explain pipeline.
pub const Stage = struct {
    kind: StageKind,
    /// Content to display (prose text, code block, metadata text, etc.).
    content: []const u8,
    /// Origin of this stage: relative source path, skill name, or "inbox".
    source: []const u8,
    /// Line number within `source` (optional, for code stages).
    line: ?u32 = null,
};

/// Releases memory associated with a stage using the provided allocator.
pub fn freeStage(allocator: std.mem.Allocator, s: Stage) void {
    allocator.free(s.content);
    allocator.free(s.source);
}

/// Releases allocated memory by freeing all stages passed to it.
pub fn freeStages(allocator: std.mem.Allocator, stages: []const Stage) void {
    for (stages) |s| freeStage(allocator, s);
}

/// Result of a sync operation (members added/updated/removed).
pub const SyncResult = struct {
    filepath: []const u8,
    members_added: usize = 0,
    members_updated: usize = 0,
    members_removed: usize = 0,
    has_changes: bool = false,
    /// True when LLM generated at least one comment for this file.
    comments_generated: bool = false,
    /// True when source file was modified (comments written to source).
    source_modified: bool = false,
};

/// Prints formatted output to stdout using a Zig formatter with specified arguments.
pub fn stepPrint(comptime fmt: []const u8, args: anytype) void {
    var buf: [512]u8 = undefined;
    const msg = std.fmt.bufPrint(&buf, fmt, args) catch return;
    std.fs.File.stdout().writeAll(msg) catch {};
}

pub const jsonifyMember = json_writer.jsonifyMember;
pub const jsonifyGuidanceDoc = json_writer.jsonifyGuidanceDoc;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test "FileType.fromExtension: zig extension maps to source" {
    try std.testing.expectEqual(FileType.source, FileType.fromExtension(".zig"));
}

test "FileType.fromExtension: py extension maps to source" {
    try std.testing.expectEqual(FileType.source, FileType.fromExtension(".py"));
}

test "FileType.fromExtension: md extension maps to markdown" {
    try std.testing.expectEqual(FileType.markdown, FileType.fromExtension(".md"));
}

test "FileType.fromExtension: json extension maps to config" {
    try std.testing.expectEqual(FileType.config, FileType.fromExtension(".json"));
}

test "FileType.fromExtension: txt extension maps to unknown" {
    try std.testing.expectEqual(FileType.unknown, FileType.fromExtension(".txt"));
}

test "FileType.fromExtension: case insensitive ZIG maps to source" {
    try std.testing.expectEqual(FileType.source, FileType.fromExtension(".ZIG"));
}

test "FileType.toStr: source round-trip" {
    try std.testing.expectEqualStrings("source", FileType.source.toStr());
}

test "FileType.toStr: markdown round-trip" {
    try std.testing.expectEqualStrings("markdown", FileType.markdown.toStr());
}

test "FileType.toStr: config round-trip" {
    try std.testing.expectEqualStrings("config", FileType.config.toStr());
}

test "FileType.toStr: unknown round-trip" {
    try std.testing.expectEqualStrings("unknown", FileType.unknown.toStr());
}

test "freeStages: no leak on empty slice" {
    const allocator = std.testing.allocator;
    const empty: []const Stage = &.{};
    freeStages(allocator, empty);
}

test "freeStages: frees all stage content" {
    const allocator = std.testing.allocator;
    var stages = try allocator.alloc(Stage, 2);
    stages[0] = .{
        .kind = .prose,
        .content = try allocator.dupe(u8, "content one"),
        .source = try allocator.dupe(u8, "src/foo.zig"),
    };
    stages[1] = .{
        .kind = .code,
        .content = try allocator.dupe(u8, "content two"),
        .source = try allocator.dupe(u8, "src/bar.zig"),
        .line = 42,
    };
    freeStages(allocator, stages);
    allocator.free(stages);
}

test "jsonifyMember: minimal fn_decl contains expected JSON fields" {
    const allocator = std.testing.allocator;
    const member = Member{
        .type = .fn_decl,
        .name = "myFunc",
        .is_pub = true,
    };
    const json = try jsonifyMember(allocator, member);
    defer if (json) |j| allocator.free(j);
    try std.testing.expect(json != null);
    const j = json.?;
    try std.testing.expect(std.mem.indexOf(u8, j, "\"type\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"fn_decl\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"name\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"myFunc\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"is_pub\"") != null);
    // Validate as JSON
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, j, .{});
    defer parsed.deinit();
}

test "jsonifyMember: special chars are escaped in name" {
    const allocator = std.testing.allocator;
    const member = Member{
        .type = .fn_decl,
        .name = "say\"hello\\world\nnew",
        .is_pub = false,
    };
    const json = try jsonifyMember(allocator, member);
    defer if (json) |j| allocator.free(j);
    try std.testing.expect(json != null);
    const j = json.?;
    try std.testing.expect(std.mem.indexOf(u8, j, "\\\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\\\\") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\\n") != null);
    // Validate as JSON
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, j, .{});
    defer parsed.deinit();
}

test "jsonifyMember: with line field included" {
    const allocator = std.testing.allocator;
    const member = Member{
        .type = .fn_decl,
        .name = "lineFunc",
        .is_pub = true,
        .line = 42,
    };
    const json = try jsonifyMember(allocator, member);
    defer if (json) |j| allocator.free(j);
    try std.testing.expect(json != null);
    const j = json.?;
    try std.testing.expect(std.mem.indexOf(u8, j, "\"line\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "42") != null);
    // Validate as JSON
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, j, .{});
    defer parsed.deinit();
}

test "jsonifyMember: with params" {
    const allocator = std.testing.allocator;
    const params = [_]Param{
        .{ .name = "alloc", .type = "std.mem.Allocator" },
        .{ .name = "val", .type = "u32", .default = "0" },
    };
    const member = Member{
        .type = .fn_decl,
        .name = "withParams",
        .is_pub = true,
        .params = &params,
    };
    const json = try jsonifyMember(allocator, member);
    defer if (json) |j| allocator.free(j);
    try std.testing.expect(json != null);
    const j = json.?;
    try std.testing.expect(std.mem.indexOf(u8, j, "\"params\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"alloc\"") != null);
    // Validate as JSON
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, j, .{});
    defer parsed.deinit();
}

test "jsonifyMember: no trailing comma when no members and no line" {
    const allocator = std.testing.allocator;
    const member = Member{
        .type = .fn_decl,
        .name = "bare",
        .is_pub = false,
    };
    const json = try jsonifyMember(allocator, member);
    defer if (json) |j| allocator.free(j);
    try std.testing.expect(json != null);
    const j = json.?;
    // Must parse as valid JSON (no trailing comma)
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, j, .{});
    defer parsed.deinit();
}

test "jsonifyMember: member comment NOT written to JSON" {
    const allocator = std.testing.allocator;
    const member = Member{
        .type = .fn_decl,
        .name = "documentedFunc",
        .is_pub = true,
        .signature = "fn documentedFunc() void",
        .comment = "This is a doc comment that should NOT appear in JSON.",
        .match_hash = "abc123",
    };
    const json = try jsonifyMember(allocator, member);
    defer if (json) |j| allocator.free(j);
    try std.testing.expect(json != null);
    const j = json.?;
    // Verify the comment field is NOT present in JSON
    try std.testing.expect(std.mem.indexOf(u8, j, "\"comment\"") == null);
    try std.testing.expect(std.mem.indexOf(u8, j, "This is a doc comment") == null);
    // Verify other fields ARE present
    try std.testing.expect(std.mem.indexOf(u8, j, "\"name\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"documentedFunc\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, j, "\"match_hash\"") != null);
    // Parse as valid JSON
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, j, .{});
    defer parsed.deinit();
}

test "jsonifyGuidanceDoc: minimal doc with just meta" {
    const allocator = std.testing.allocator;
    const doc = GuidanceDoc{
        .meta = .{
            .module = "mymod",
            .source = "src/mymod.zig",
        },
    };
    const json = try jsonifyGuidanceDoc(allocator, doc);
    defer allocator.free(json);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"meta\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"mymod\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"src/mymod.zig\"") != null);
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, json, .{});
    defer parsed.deinit();
}

test "jsonifyGuidanceDoc: doc with comment and keywords" {
    const allocator = std.testing.allocator;
    const kws = [_][]const u8{ "alpha", "beta" };
    const doc = GuidanceDoc{
        .meta = .{
            .module = "things",
            .source = "src/things.zig",
        },
        .comment = "Does things.",
        .keywords = &kws,
    };
    const json = try jsonifyGuidanceDoc(allocator, doc);
    defer allocator.free(json);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"comment\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "Does things.") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"keywords\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"alpha\"") != null);
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, json, .{});
    defer parsed.deinit();
}
