#!/usr/bin/env python3
"""Generate 64x384 random unit vectors for SimHash random projection LSH.

These are stored as a comptime Zig array in src/vector/simhash_projections.zig.
The seed is fixed (42) — never change it, as doing so invalidates all existing
simhash_index rows in every .guidance.db.

Usage:
    python3 tools/gen_simhash_projections.py > src/vector/simhash_projections.zig
"""

import numpy as np
import sys

BITS = 64
DIMS = 384
SEED = 42

rng = np.random.default_rng(seed=SEED)
vecs = rng.standard_normal((BITS, DIMS)).astype(np.float32)
# Normalize each row to unit length so dot products become cosine projections.
norms = np.linalg.norm(vecs, axis=1, keepdims=True)
vecs /= norms

out = sys.stdout
out.write("/// simhash_projections.zig — auto-generated by tools/gen_simhash_projections.py\n")
out.write("/// DO NOT EDIT — regenerating invalidates all existing simhash_index rows.\n")
out.write("/// Seed: 42, Bits: 64, Dims: 384\n")
out.write("pub const data: [64][384]f32 = .{\n")
for row_i in range(BITS):
    out.write("    .{")
    vals = vecs[row_i]
    parts = []
    for v in vals:
        # Emit as hex float literal so no precision is lost in the round-trip.
        parts.append(f"{v:.9e}")
    out.write(", ".join(parts))
    out.write("},\n")
out.write("};\n")
