/// simhash.zig — Charikar SimHash for approximate nearest-neighbour pre-filtering.
///
/// Random projection LSH: each of 64 bits encodes the sign of a dot product
/// between the input embedding and a fixed random unit vector.  Two vectors
/// that are close in cosine space tend to agree on most bits.
///
/// Hamming distance (XOR + popcount) provides a fast O(1) approximation to
/// cosine distance, turning the full KNN scan into a cheap bucket test.
///
/// Guarantees (empirical at 64 bits, 384 dims):
///   cosine ≥ 0.70 → hamming ≤ ~12 bits  (≈95% recall)
///   cosine ≥ 0.50 → hamming ≤ ~18 bits  (≈90% recall)
///
/// The PROJECTIONS constant is generated once (seed=42) and must never be
/// regenerated without also rebuilding every simhash_index table.  The
/// generation script is tools/gen_simhash_projections.py.
///
/// Embedding dimension: hard-coded to 384 to match the most common edge
/// embedding model (all-MiniLM-L6-v2, nomic-embed-text).  If your embedder
/// produces 768 or 1536 dimensions, only the first 384 are used for hashing.
const std = @import("std");

/// Number of hash bits (= number of random projection vectors).
pub const SIMHASH_BITS: usize = 64;

/// Embedding dimension for which the projections were generated.
/// Embeddings shorter than this are zero-padded implicitly (ignored dims).
pub const SIMHASH_DIMS: usize = 384;

/// 64 × 384 random unit vectors, seeded with numpy rng(42).
/// Generated by tools/gen_simhash_projections.py.
pub const PROJECTIONS: [SIMHASH_BITS][SIMHASH_DIMS]f32 =
    @import("simhash_projections.zig").data;

/// Computes a SHA-256 hash from an embedding array and returns a 64-bit unsigned value.
pub fn simhash(embedding: []const f32) u64 {
    const effective_len = @min(embedding.len, SIMHASH_DIMS);
    var h: u64 = 0;
    for (PROJECTIONS, 0..) |proj, i| {
        var dot: f32 = 0.0;
        for (proj[0..effective_len], embedding[0..effective_len]) |p, e| {
            dot += p * e;
        }
        if (dot > 0.0) h |= (@as(u64, 1) << @as(u6, @intCast(i)));
    }
    return h;
}

/// Calculates the Hamming distance between two u64 integers, returning a 7-bit unsigned value.
pub inline fn hammingDistance(a: u64, b: u64) u7 {
    return @popCount(a ^ b);
}

/// Computes the maximum Hamming distance between two cosine thresholds, returning a 7-bit unsigned integer.
pub fn maxHamming(cosine_threshold: f32) u7 {
    const f_bits: f32 = @floatFromInt(SIMHASH_BITS);
    const raw = f_bits * (1.0 - cosine_threshold) * 0.85;
    const rounded: u7 = @intFromFloat(@ceil(raw));
    return rounded;
}

// =============================================================================
// Tests
// =============================================================================

const testing = std.testing;

test "simhash: deterministic for identical input" {
    // A simple non-zero embedding of length SIMHASH_DIMS.
    var emb: [SIMHASH_DIMS]f32 = undefined;
    for (&emb, 0..) |*v, i| v.* = @as(f32, @floatFromInt(i % 7)) * 0.1;

    const h1 = simhash(&emb);
    const h2 = simhash(&emb);
    try testing.expectEqual(h1, h2);
}

test "simhash: zero embedding gives 0" {
    const emb: [SIMHASH_DIMS]f32 = [_]f32{0.0} ** SIMHASH_DIMS;
    // All dot products are 0, so no bit is set (dot > 0 condition fails).
    try testing.expectEqual(@as(u64, 0), simhash(&emb));
}

test "simhash: orthogonal embeddings differ in ~32 bits" {
    // e1 all-positive, e2 all-negative → roughly half the projections flip.
    var e1: [SIMHASH_DIMS]f32 = [_]f32{1.0} ** SIMHASH_DIMS;
    var e2: [SIMHASH_DIMS]f32 = [_]f32{-1.0} ** SIMHASH_DIMS;
    const h1 = simhash(&e1);
    const h2 = simhash(&e2);
    // They should be bitwise complements — all 64 bits differ.
    try testing.expectEqual(@as(u64, 64), hammingDistance(h1, h2));
}

test "hammingDistance: same hash → 0" {
    try testing.expectEqual(@as(u7, 0), hammingDistance(0xDEADBEEF_CAFEBABE, 0xDEADBEEF_CAFEBABE));
}

test "hammingDistance: all bits differ → 64" {
    try testing.expectEqual(@as(u7, 64), hammingDistance(0, ~@as(u64, 0)));
}

test "hammingDistance: single bit differs → 1" {
    try testing.expectEqual(@as(u7, 1), hammingDistance(0b0, 0b1));
}

test "maxHamming: higher threshold → fewer allowed bits" {
    const h_strict = maxHamming(0.90);
    const h_loose = maxHamming(0.28);
    try testing.expect(h_strict < h_loose);
}

test "maxHamming: threshold 1.0 → 0 bits" {
    try testing.expectEqual(@as(u7, 0), maxHamming(1.0));
}

test "simhash: short embedding (shorter than DIMS) doesn't panic" {
    const short: [10]f32 = [_]f32{0.5} ** 10;
    _ = simhash(&short); // must not panic or overflow
}



